const AUTH_TYPES = {
    PAGE_AUTH: 'PAGE_AUTH',
    REQUEST_AUTH: 'REQUEST_AUTH',
    INITIAL_AUTH: 'INITIAL_AUTH'
}

const USER_LIST_LIMIT = 10;

module.exports = {
    AUTH_TYPES,
    USER_LIST_LIMIT
}